name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [rust-compressor, js-compressor]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.project }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.project }}:${{ github.sha }}

      - name: Run tests
        run: |
          if [ "${{ matrix.project }}" = "rust-compressor" ]; then
            cd rust-compressor && cargo test
          else
            cd js-compressor
            npm install
            npx mocha test/*.test.js
          fi
