name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [rust-compressor, js-compressor]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: lele-maxwell # <-- your GitHub username
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.project }}
          push: true
          tags: |
            ghcr.io/lele-maxwell/${{ matrix.project }}:latest
            ghcr.io/lele-maxwell/${{ matrix.project }}:${{ github.sha }}

      - name: Run tests
        run: |
          if [ "${{ matrix.project }}" = "rust-compressor" ]; then
            cd rust-compressor && cargo test
          else
            cd js-compressor && npm test
          fi
